# Generated by Django 3.2.18 on 2023-03-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CampaingHints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/campaigns/hints/')),
            ],
        ),
        migrations.CreateModel(
            name='Influencers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('instagram_link', models.URLField(verbose_name='link to the ')),
                ('profile_image', models.ImageField(upload_to='images/influencers/profile_images/')),
                ('campaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='images/influencers/post_images/')),
                ('post_image_processed', models.ImageField(blank=True, null=True, upload_to='images/influencers/post_images/processed/')),
                ('post_link', models.URLField(verbose_name='link to the ')),
                ('post_description', models.CharField(max_length=2200)),
                ('post_sentiment', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='sentiment of the post')),
                ('post_subjectivity', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='subjectivity of the post')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.influencers')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2200)),
                ('sentiment', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='sentiment of the comment')),
                ('subjectivity', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='subjectivity of the comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.posts')),
            ],
        ),
    ]
